### PR TITLE
Create blank.yml

### PR DESCRIPTION
**Pull request by 0958436455sarayut**

### CODE REVIEW

**Review by nxa6 — CHANGES_REQUESTED** [review]
> ``

**Review by nxa6 — COMMENTED** [review]
hh

**Review by Mgthanlwin — APPROVED** [review]

**Review by Bignicc36 — CHANGES_REQUESTED** [review]
Pull this please due to improper tracking methods

**Review by toxxicandco2 — APPROVED** [review]

**Comment by 0958436455sarayut** [comment]
From 97274a86ca1539488fb30af94c2377e53042b682 Mon Sep 17 00:00:00 2001
From: 0958436455sarayut <65490490+0958436455sarayut@users.noreply.github.com>
Date: Thu, 17 Jun 2021 18:55:47 +0700
Subject: [PATCH] Create blank.yml

---
 .github/workflows/blank.yml | 36 ++++++++++++++++++++++++++++++++++++
 1 file changed, 36 insertions(+)
 create mode 100644 .github/workflows/blank.yml

diff --git a/.github/workflows/blank.yml b/.github/workflows/blank.yml
new file mode 100644
index 0000000..7855d5e
--- /dev/null
+++ b/.github/workflows/blank.yml
@@ -0,0 +1,36 @@
+# This is a basic workflow to help you get started with Actions
+
+name: CI
+
+# Controls when the action will run. 
+on:
+  # Triggers the workflow on push or pull request events but only for the main branch
+  push:
+    branches: [ main ]
+  pull_request:
+    branches: [ main ]
+
+  # Allows you to run this workflow manually from the Actions tab
+  workflow_dispatch:
+
+# A workflow run is made up of one or more jobs that can run sequentially or in parallel
+jobs:
+  # This workflow contains a single job called "build"
+  build:
+    # The type of runner that the job will run on
+    runs-on: ubuntu-latest
+
+    # Steps represent a sequence of tasks that will be executed as part of the job
+    steps:
+      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
+      - uses: actions/checkout@v2
+
+      # Runs a single command using the runners shell
+      - name: Run a one-line script
+        run: echo Hello, world!
+
+      # Runs a set of commands using the runners shell
+      - name: Run a multi-line script
+        run: |
+          echo Add other actions to build,
+          echo test, and deploy your project.

**Comment by 0958436455sarayut** [comment]
@@ -0,0 +1,36 @@
￼# This is a basic workflow to help you get started with Actions
￼
￼name: CI
￼
￼# Controls when the action will run. 
￼on:
￼  # Triggers the workflow on push or pull request events but only for the main branch
￼  push:
￼    branches: [ main ]
￼  pull_request:
￼    branches: [ main ]
￼
￼  # Allows you to run this workflow manually from the Actions tab
￼  workflow_dispatch:
￼
￼# A workflow run is made up of one or more jobs that can run sequentially or in parallel
￼jobs:
￼  # This workflow contains a single job called "build"
￼  build:
￼    # The type of runner that the job will run on
￼    runs-on: ubuntu-latest
￼
￼    # Steps represent a sequence of tasks that will be executed as part of the job
￼    steps:
￼      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
￼      - uses: actions/checkout@v2
￼
￼      # Runs a single command using the runners shell
￼      - name: Run a one-line script
￼        run: echo Hello, world!
￼
￼      # Runs a set of commands using the runners shell
￼      - name: Run a multi-line script
￼        run: |
￼          echo Add other actions to build,
￼          echo test, and deploy your project.

**Pull request closed without merging**
