### PR TITLE
Update android.yml

### PR DESCRIPTION
**Pull request by codingjeremy**

### CODE REVIEW

**Comment by Alexander809** [comment]
@codingjeremy

**Review by nic0lette — APPROVED** [review]

**Review by lukmangrd — COMMENTED** [review]
#23

**Comment by jasawan** [comment]
android 11

**Review by jasawan — COMMENTED** [review]
[consule 
](https://firebase.google.com/codelabs/firebase-android#0)

**Review by Jccp1983 — APPROVED** [review]

**Comment by unreal-person-666** [comment]
#

**Pull request merged**
