### PR TITLE
Update yaml category

### PR DESCRIPTION
**Pull request by codingjeremy**

### CODE REVIEW

**Comment by unreal-person-666** [comment]
27d9603b5cf5cfa059298748f2711ef3306388a0

**Review by kayal28 — COMMENTED** [review]
Wireless

**Review by kayal28 — COMMENTED** [review]
Download

**Review by HEXYEBO0 — APPROVED** [review]

**Review by HEXYEBO0 — APPROVED** [review]
b8beff3f746a86fd07f3d9f07838761cb3ad5157

**Pull request merged**
